
name: Playwright tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  
  # TODO: uncomment to make the tests run on every PR
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # Runs on an ubuntu runner
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Install SWA and Azure Function tool
      run: npm install -g @azure/static-web-apps-cli azure-functions-core-tools
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run playwright tests
      run: npm run playwright_test
    - name: Upload HTML report as Artifact
      uses: actions/upload-artifact@v3
      with: 
        name: test-report
        path: pw-report/